[package]
name = "filter"
version = "0.1.0"
authors = ["Michael Mauderer <michael@michaelmauderer.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.17.0"
num-traits = "0.2"
assert_approx_eq = "1.1.0"
