name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests for no_std
      run: cargo test --verbose --no-default-features
    - name: Install `cargo-nono`
      run: cargo install cargo-nono
    - name: Test that the library (and all dependencies) work for no_std
      run: cargo nono check
